### ISSUE TITLE
OS_concecpts/OS.md에 오타 및 사진 linked error

### ISSUE THREAD

**Issue by siwony** [lot8229/TodayILearn#2]
### 1. 오타
![image](https://user-images.githubusercontent.com/62932968/123517927-ab4d8480-d6de-11eb-8884-d7f31d719ac7.png)

즉각 수정바랍니다.

**Comment by coodns** [comment]
### 1 .오타

해결 했습니다.

### 2. Linked Error 

해당 Issue 는 당신의 문제인것 같습니다.
