### ISSUE TITLE
사실 클로저는 자바스크립트만이 가지고 있는 고유한 개념 같은게 아니랍니다 ? 🧐

### ISSUE THREAD

**Issue by Nayejun** [lot8229/TodayILearn#8]
https://github.com/codnstj/TodayILearn/blob/3697393e87f47e6e60e4c2ff53a069a432870abb/JS/closure.md

사실 클로저는 자바스크립트만이 가지고 있는 고유한 개념 같은게 아니랍니다 ? 🧐

본질은 “함수가 선언됐을 때의 렉시컬 환경(Lexical environment)”이다. 랍니다 ? 😋

`“A closure is the combination of a function and the lexical environment within which that function was declared.”`

**Comment by coodns** [comment]
음 몰랐네요 ㅎㅎ 알려주셔서 감사합니다!
